### ISSUE TITLE
Link is not working 

### ISSUE THREAD

**Issue by whamwi** [lufcmattylad/Summary-Card-Template-Component#1]
Please check the code regarding the link button on the card, it does not seem to work, it just refreshes the page although on your demo page, it works, while installing the plug in, it does not work

thank,

**Comment by lufcmattylad** [comment]
Hi @whamwi 
I think I've found the problem & I'll issue a new version in the coming days. However as a workaround....
1. Edit the plugin in Shared Components
2. Find the "Partial" section
3. Change this Line
`<button class="rc-btn btn__continue" data-link="#LINK#">#LINK_TEXT#</button>`
to this 
`<button type="button" onclick="void(0);" class="rc-btn btn__continue" data-link="#LINK#">#LINK_TEXT#</button>`
4. Click Apply Changes

**Comment by lufcmattylad** [comment]
Resolved in release v23.2.1
